name: Vespa Blog Search Feed
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1
        bundler-cache: true

    - name: Build site
      run: |
        bundle exec jekyll build -p _plugins-vespafeed

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Feed site
      env:
        VESPA_TEAM_DATA_PLANE_PUBLIC_CERT: ${{ secrets.VESPA_TEAM_DATA_PLANE_PUBLIC_CERT }}
        VESPA_TEAM_DATA_PLANE_PRIVATE_KEY: ${{ secrets.VESPA_TEAM_DATA_PLANE_PRIVATE_KEY }}
      run: |
        pip3 install PyYAML
        ./feed_to_vespa.py
